### PR TITLE
Git learning

### PR DESCRIPTION
**Pull request by jonrichfield**
Having problems mastering git. Here is where I express.... thingummy

### CODE REVIEW

**Comment by slashme** [comment]
Not sure why this ended up as a pull request. Merging anyway.

**Comment by jonrichfield** [comment]
OK, but I had been hoping that there was a way to split a project so that there are separate branches on separable topics. <br>For example, we might want to have a particular (permanent) branch for each of Git, Atom, Python and Apache (just say!)<br>Meanwhile I see that \<br\> works for line breaking and that the backslash works in permitting me to cancel  control character function; not that I need it much here, only it is nice to know what works and what doesn't work so well.

**Comment by slashme** [comment]
Topic branches are a basic functionality of git. I've just done it:

```
david@davelaptop:~/dev/Initiation$ git branch featuretest
david@davelaptop:~/dev/Initiation$ git push origin featuretest 
```

You will now see that there is a new branch called featuretest, that is currently pointing to the same place as "master":
```
david@davelaptop:~/dev/Initiation$ git branch 
  featuretest
* master
```
What you can do now is to pull that branch into your local repository - I haven't checked how to do this through the gui, but on the command line, it's "git fetch", and if you want to make changes to the feature branch, you need to check it out:
```
david@davelaptop:~/dev/Initiation$ git checkout featuretest 
Switched to branch 'featuretest'
david@davelaptop:~/dev/Initiation$ git branch
* featuretest
  master
```

OK, and now I noticed that in the rename, I forgot to add the renamed file, so I've added it back on the master branch. That means that the featuretest branch is now one commit back from the master. That's a happy accident: now you can make a change on the featuretest branch, fetch the changes from master into featuretest, and then merge featuretest back into master.  How this would go:

```
david@davelaptop:~/dev/Initiation$ git checkout featuretest 
Switched to branch 'featuretest'
```

Created a "feature test" branch.

```
david@davelaptop:~/dev/Initiation$ touch feature.md
david@davelaptop:~/dev/Initiation$ ls
feature.md  README.md
```
Created an empty file called "feature.md"

```
david@davelaptop:~/dev/Initiation$ git status 
On branch featuretest
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        feature.md

nothing added to commit but untracked files present (use "git add" to track)
```

So now the new file is sitting there, but git isn't tracking it yet.

```
david@davelaptop:~/dev/Initiation$ git add feature.md 
david@davelaptop:~/dev/Initiation$ git commit -m "Added feature"
[featuretest 6792328] Added feature
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 feature.md
```
Added the file and committed it to the feature branch.

```
david@davelaptop:~/dev/Initiation$ git checkout master -- Teething\ troubles\ with\ Git.md
```
What I've done here is to grab the Teething troubles file (which at the moment only exists on the master branch) 

```
david@davelaptop:~/dev/Initiation$ ls
feature.md  README.md  Teething troubles with Git.md
david@davelaptop:~/dev/Initiation$ git status 
On branch featuretest
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   Teething troubles with Git.md
```
And now, as you can see, it's there in the directory, and git sees it as a brand new file on the feature branch, so I need to add it and commit that change to the feature branch.

```
david@davelaptop:~/dev/Initiation$ git add Teething\ troubles\ with\ Git.md 
david@davelaptop:~/dev/Initiation$ git commit -m "Grab new file from master"
[featuretest e74d666] Grab new file from master
 1 file changed, 12 insertions(+)
 create mode 100644 Teething troubles with Git.md
```

Right, now the "feature" branch is the same as the "master" branch, except that it has the "feature.md" file. So now to merge the feature branch into master:

```
david@davelaptop:~/dev/Initiation$ git checkout master 
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
david@davelaptop:~/dev/Initiation$ git merge featuretest 
Merge made by the 'recursive' strategy.
 feature.md | 0
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 feature.md
```

And now we're on the mater branch, and the feature.md file is there:
```
david@davelaptop:~/dev/Initiation$ ls
feature.md  README.md  Teething troubles with Git.md
```

Note, I did this all locally: I didn't push those changes to origin, because I want to leave it to you to see whether you can manage to merge the feature branch into the master branch.

**Comment by slashme** [comment]
Different parts of the project (e.g. Apache, Git, etc.) should live in subdirectories. Branches are used to keep different versions of the whole project, for example a new feature that isn't ready for prime time.

**Pull request merged**
